### ISSUE TITLE
Compare mode not working

### ISSUE THREAD

**Issue by hanokkurian** [friendsofagape/autographa-live#102]
Autographa Live
Version 0.1.0-beta.7

My Translation Language code is **Punjabi (pan)**
Then  added reference text with **language code Punjabi (pan)**

when click to Compare mode on 
message shows "**Unable to Show Comparison** 
Compare mode is not meaningful across different languages. Please ensure you have set the translation details in Settings and selected the same language across all panes."

![1](https://user-images.githubusercontent.com/25005190/69475039-5ce35000-0dee-11ea-97d9-876da3796686.png)
![2](https://user-images.githubusercontent.com/25005190/69475051-856b4a00-0dee-11ea-9562-363c00382a12.png)

**Comment by Ashersam** [comment]
![Screenshot from 2020-01-10 15-46-53](https://user-images.githubusercontent.com/38970117/72145582-d34d0900-33c0-11ea-97d7-8ad755bda9d2.png)
![Screenshot from 2020-01-10 15-47-02](https://user-images.githubusercontent.com/38970117/72145583-d3e59f80-33c0-11ea-9e2d-f8602361e901.png)
![Screenshot from 2020-01-10 15-47-21](https://user-images.githubusercontent.com/38970117/72145585-d3e59f80-33c0-11ea-9cfe-16a8b83e90a8.png)

**Comment by Ashersam** [comment]
Sorry, I'm not able to recreate the issue. Compare works fines for both beta7 and beta 8

**Comment by joelthe1** [comment]
This is fixed.
